---
title: "Supplementary"
toc: false
format: 
  html:
    page-layout: article
---

Details of the three evaluations categories with metric and range in this study.

+-----------------------------------------------+--------------------------------+-------------------+---------------------------+-------------------------------------+
| Evaluation                                    | Task                           | Transformation    | Metric                    | Range                               |
+===============================================+================================+===================+===========================+=====================================+
| Data properties                               | Library size                   | No                | Kernel Density Scores     | \[0, infinity) then map to \[0, 1\] |
|                                               |                                |                   |                           |                                     |
|                                               | TMM                            | NO                |                           |                                     |
|                                               |                                |                   |                           |                                     |
|                                               | Effective library size         | NO                |                           |                                     |
+-----------------------------------------------+--------------------------------+-------------------+---------------------------+-------------------------------------+
|                                               |                                |                   |                           |                                     |
+-----------------------------------------------+--------------------------------+-------------------+---------------------------+-------------------------------------+
|                                               |                                |                   |                           |                                     |
+-----------------------------------------------+--------------------------------+-------------------+---------------------------+-------------------------------------+
|                                               |                                |                   |                           |                                     |
+-----------------------------------------------+--------------------------------+-------------------+---------------------------+-------------------------------------+
|                                               |                                |                   |                           |                                     |
+-----------------------------------------------+--------------------------------+-------------------+---------------------------+-------------------------------------+
|                                               |                                |                   |                           |                                     |
+-----------------------------------------------+--------------------------------+-------------------+---------------------------+-------------------------------------+
|                                               |                                |                   |                           |                                     |
+-----------------------------------------------+--------------------------------+-------------------+---------------------------+-------------------------------------+
| Mean vs variance (scale)                      | Yes, log-normal transformation |                   |                           |                                     |
+-----------------------------------------------+--------------------------------+-------------------+---------------------------+-------------------------------------+
|                                               |                                |                   |                           |                                     |
+-----------------------------------------------+--------------------------------+-------------------+---------------------------+-------------------------------------+
| Mean vs fraction zero                         | No                             |                   |                           |                                     |
+-----------------------------------------------+--------------------------------+-------------------+---------------------------+-------------------------------------+
|                                               |                                |                   |                           |                                     |
+-----------------------------------------------+--------------------------------+-------------------+---------------------------+-------------------------------------+
| Gene Pearson correlation                      | No                             |                   |                           |                                     |
+-----------------------------------------------+--------------------------------+-------------------+---------------------------+-------------------------------------+
|                                               |                                |                   |                           |                                     |
+-----------------------------------------------+--------------------------------+-------------------+---------------------------+-------------------------------------+
| Transition Matrix (TM)                        | No                             |                   |                           |                                     |
+-----------------------------------------------+--------------------------------+-------------------+---------------------------+-------------------------------------+
|                                               |                                |                   |                           |                                     |
+-----------------------------------------------+--------------------------------+-------------------+---------------------------+-------------------------------------+
| Neighborhood enrichment matrix (NEM)          | No                             |                   |                           |                                     |
+-----------------------------------------------+--------------------------------+-------------------+---------------------------+-------------------------------------+
|                                               |                                |                   |                           |                                     |
+-----------------------------------------------+--------------------------------+-------------------+---------------------------+-------------------------------------+
| Centralized score matrix (CSM)                | No                             |                   |                           |                                     |
+-----------------------------------------------+--------------------------------+-------------------+---------------------------+-------------------------------------+
|                                               |                                |                   |                           |                                     |
+-----------------------------------------------+--------------------------------+-------------------+---------------------------+-------------------------------------+
| Cell type interaction                         | No                             |                   |                           |                                     |
+-----------------------------------------------+--------------------------------+-------------------+---------------------------+-------------------------------------+
|                                               |                                |                   |                           |                                     |
+-----------------------------------------------+--------------------------------+-------------------+---------------------------+-------------------------------------+
| Moran’s I                                     | No                             |                   |                           |                                     |
+-----------------------------------------------+--------------------------------+-------------------+---------------------------+-------------------------------------+
|                                               |                                |                   |                           |                                     |
+-----------------------------------------------+--------------------------------+-------------------+---------------------------+-------------------------------------+
| L statistics                                  | No                             |                   |                           |                                     |
+-----------------------------------------------+--------------------------------+-------------------+---------------------------+-------------------------------------+
|                                               |                                |                   |                           |                                     |
+-----------------------------------------------+--------------------------------+-------------------+---------------------------+-------------------------------------+
| Nearest neighbor correlation                  | No                             |                   |                           |                                     |
+-----------------------------------------------+--------------------------------+-------------------+---------------------------+-------------------------------------+
|                                               |                                |                   |                           |                                     |
+-----------------------------------------------+--------------------------------+-------------------+---------------------------+-------------------------------------+
| Spatial downstream analysis                   | Spatial clustering             | No                | Adjusted rand index (ARI) | \[-1, 1\]                           |
+-----------------------------------------------+--------------------------------+-------------------+---------------------------+-------------------------------------+
|                                               |                                |                   |                           |                                     |
+-----------------------------------------------+--------------------------------+-------------------+---------------------------+-------------------------------------+
|                                               |                                |                   |                           |                                     |
+-----------------------------------------------+--------------------------------+-------------------+---------------------------+-------------------------------------+
|                                               |                                |                   |                           |                                     |
+-----------------------------------------------+--------------------------------+-------------------+---------------------------+-------------------------------------+
|                                               |                                |                   |                           |                                     |
+-----------------------------------------------+--------------------------------+-------------------+---------------------------+-------------------------------------+
|                                               |                                |                   |                           |                                     |
+-----------------------------------------------+--------------------------------+-------------------+---------------------------+-------------------------------------+
|                                               |                                |                   |                           |                                     |
+-----------------------------------------------+--------------------------------+-------------------+---------------------------+-------------------------------------+
|                                               |                                |                   |                           |                                     |
+-----------------------------------------------+--------------------------------+-------------------+---------------------------+-------------------------------------+
| Spatially variable genes (SVG) identification | No                             | Precision         | \[0, 1\]                  |                                     |
+-----------------------------------------------+--------------------------------+-------------------+---------------------------+-------------------------------------+
|                                               |                                |                   |                           |                                     |
+-----------------------------------------------+--------------------------------+-------------------+---------------------------+-------------------------------------+
| No                                            | Recall                         | \[0, 1\]          |                           |                                     |
+-----------------------------------------------+--------------------------------+-------------------+---------------------------+-------------------------------------+
|                                               |                                |                   |                           |                                     |
+-----------------------------------------------+--------------------------------+-------------------+---------------------------+-------------------------------------+
| Spatial cross-correlation                     | No                             | Cosine similarity | \[-1, 1\]                 |                                     |
+-----------------------------------------------+--------------------------------+-------------------+---------------------------+-------------------------------------+
|                                               |                                |                   |                           |                                     |
+-----------------------------------------------+--------------------------------+-------------------+---------------------------+-------------------------------------+
| No                                            | Mental statistics              | \[-1, 1\]         |                           |                                     |
+-----------------------------------------------+--------------------------------+-------------------+---------------------------+-------------------------------------+
|                                               |                                |                   |                           |                                     |
+-----------------------------------------------+--------------------------------+-------------------+---------------------------+-------------------------------------+
| Scalability                                   | 200 x 200                      | No                | time                      | \[0, infinity)                      |
|                                               |                                |                   |                           |                                     |
|                                               | 3k x 500                       |                   |                           |                                     |
|                                               |                                |                   |                           |                                     |
|                                               | 5k x 1k                        |                   |                           |                                     |
+-----------------------------------------------+--------------------------------+-------------------+---------------------------+-------------------------------------+
|                                               |                                |                   |                           |                                     |
+-----------------------------------------------+--------------------------------+-------------------+---------------------------+-------------------------------------+
| No                                            | memory                         | \[0, infinity)    |                           |                                     |
+-----------------------------------------------+--------------------------------+-------------------+---------------------------+-------------------------------------+
|                                               |                                |                   |                           |                                     |
+-----------------------------------------------+--------------------------------+-------------------+---------------------------+-------------------------------------+
