---
title: "Summary"
format:
  html:
    code-link: true
editor: visual
toc: false
---


```{ojs}
//| echo: false

funkyheatmap = (await require('d3@7').then(d3 => {

  window.d3 = d3;

  window._ = _;

  return import('https://unpkg.com/funkyheatmapjs@0.2.5');

})).default;

```


```{r setup}
#| label: load-packages
#| include: false
#| error: true
#| echo: false

library(tidyverse)
library(funkyheatmap)
library(kableExtra)
library(readr)
library(DT)
library(plotly)
library(jsonlite)
``` 



```{ojs}
//| label: read data
//| warning: false
//| echo: false

viewof color_by_rank = Inputs.toggle({label: "Color by rank:", value: true})
viewof scale_column = Inputs.toggle({label: "Minmax column:", value: false})
viewof show_con = Inputs.toggle({label: "Show control methods:", value: true})

/* 
async function loadData() {
  try {
    const final_data = await FileAttachment("./data/final_data2.csv").csv()
    const column_info = await FileAttachment("./data/column_info.csv").csv()
    const column_groups = await FileAttachment("./data/column_groups.csv").csv()
    //const palettes = await FileAttachment("./data/palettes.csv").csv()

    console.log("FINAL DATA", final_data)
    console.log("COLUMN INFO", column_info)
    console.log("COLUMN GROUPS", column_groups)
    //console.log("palettes", palettes)


    const palettes = [
    {
        overall: "Greys",
        palette1: "Set1",
        palette2: "Set2",
        palette3: "Set3",
        palette4: "Blues",
        NA: "Greens",
        white6black4: "Dark2",
        error_reason: {
          colors: ["#8DD3C7", "#FFFFB3", "#BEBADA", "#FFFFFF"],
          names: ["Memory limit exceeded", "Time limit exceeded", "Execution error", "No error"]
        }
      }
    ][0] 

    function transpose_list_of_objects(list) {
      return Object.fromEntries(Object.keys(list[0]).map(key => [key, list.map(d => d[key])]))
    }

    console.log("TRANSPOSE FINAL DATA", transpose_list_of_objects(final_data))
    console.log("TRANSPOSE COLUMN INFO", transpose_list_of_objects(column_info))
    console.log("TRANSPOSE COLUMN GROUPS", transpose_list_of_objects(column_groups))

    funkyheatmap(
      transpose_list_of_objects(final_data),
      transpose_list_of_objects(column_info),
      [],
      transpose_list_of_objects(column_groups),
      [],
      palettes,
      {
          fontSize: 14,
          rowHeight: 26,
          rootStyle: 'max-width: none',
          colorByRank: color_by_rank,
          theme: {
              oddRowBackground: 'var(--bs-body-bg)',
              evenRowBackground: 'var(--bs-button-hover)',
              textColor: 'var(--bs-body-color)',
              strokeColor: 'var(--bs-body-color)',
              headerColor: 'var(--bs-body-color)',
              hoverColor: 'var(--bs-body-color)'
          }
      }
    );

    
  
  //final_data.view()

  } catch (error) {
    console.error("Error loading data:", error);
  }
}

loadData() */

final_data = FileAttachment("./data/final_data2.csv").csv()
column_info = await FileAttachment("./data/column_info.csv").csv()
column_groups = await FileAttachment("./data/column_groups.csv").csv()


p1 = ["#6ABAC4,#6BBAC4,#6DBBC5,#6EBCC5,#70BCC6,#71BDC6,#73BEC7,#74BEC8,#76BFC8,#77C0C9,#79C0C9,#7AC1CA,#7CC2CB,#7DC3CB,#7FC3CC,#80C4CC,#82C5CD,#83C5CE,#85C6CE,#86C7CF,#88C7CF,#89C8D0,#8BC9D1,#8CCAD1,#8ECAD2,#8FCBD2,#91CCD3,#92CCD4,#94CDD4,#95CED5,#97CED5,#98CFD6,#9AD0D7,#9BD1D7,#9DD1D8,#9ED2D8,#A0D3D9,#A1D3DA,#A3D4DA,#A4D5DB,#A6D5DB,#A7D6DC,#A9D7DD,#AAD7DD,#ACD8DE,#ADD9DE,#AFDADF,#B0DAE0,#B2DBE0,#B3DCE1,#B5DCE1,#B6DDE2,#B8DEE2,#B9DEE3,#BBDFE4,#BCE0E4,#BEE1E5,#BFE1E5,#C1E2E6,#C2E3E7,#C4E3E7,#C5E4E8,#C7E5E8,#C8E5E9,#CAE6EA,#CBE7EA,#CDE8EB,#CEE8EB,#D0E9EC,#D1EAED,#D3EAED,#D4EBEE,#D6ECEE,#D7ECEF,#D9EDF0,#DAEEF0,#DCEEF1,#DDEFF1,#DFF0F2,#E0F1F3,#E2F1F3,#E3F2F4,#E5F3F4,#E6F3F5,#E8F4F6,#E9F5F6,#EBF5F7,#ECF6F7,#EEF7F8,#EFF8F9,#F1F8F9,#F2F9FA,#F4FAFA,#F5FAFB,#F7FBFC,#F8FCFC,#FAFCFD,#FBFDFD,#FDFEFE,#FFFFFF"]

palettes = [
    {
        overall: "Greys",
        palette1: "Greens",
        palette2: "Blues",
        palette3: "Greens",
        palette4: "Blues",
        NA: "Greens",
        white6black4: "Greys",
        error_reason: {
          colors: ["#8DD3C7", "#FFFFB3", "#BEBADA", "#FFFFFF"],
          names: ["Memory limit exceeded", "Time limit exceeded", "Execution error", "No error"]
        }
      }
    ][0] 

function transpose_list_of_objects(list) {
      return Object.fromEntries(Object.keys(list[0]).map(key => [key, list.map(d => d[key])]))
    }

console.log(final_data)


funkyheatmap(
      transpose_list_of_objects(final_data),
      transpose_list_of_objects(column_info),
      [],
      transpose_list_of_objects(column_groups),
      [],
      palettes,
      {
          fontSize: 14,
          rowHeight: 26,
          rootStyle: 'max-width: none',
          colorByRank: color_by_rank,
          theme: {
              oddRowBackground: 'var(--bs-body-bg)',
              evenRowBackground: 'var(--bs-button-hover)',
              textColor: 'var(--bs-body-color)',
              strokeColor: 'var(--bs-body-color)',
              headerColor: 'var(--bs-body-color)',
              hoverColor: 'var(--bs-body-color)'
          }
      }
    );






<!-- rank_based_summary <- function(subset_data) { -->
<!--   ranked_data <- apply(subset_data, 2, function(x) rank(x))  # Rank such that larger values get higher ranks -->
<!--   rowMeans(ranked_data) -->
<!-- } -->

```

## Results

<!-- ```{ojs}
//| echo: false
//| warning: false
//| column: page
//| layout-ncol: 1
//| fig-width: 10
//| fig-height: 8

 /* p1 = "#6ABAC4,#6BBAC4,#6DBBC5,#6EBCC5,#70BCC6,#71BDC6,#73BEC7,#74BEC8,#76BFC8,#77C0C9,#79C0C9,#7AC1CA,#7CC2CB,#7DC3CB,#7FC3CC,#80C4CC,#82C5CD,#83C5CE,#85C6CE,#86C7CF,#88C7CF,#89C8D0,#8BC9D1,#8CCAD1,#8ECAD2,#8FCBD2,#91CCD3,#92CCD4,#94CDD4,#95CED5,#97CED5,#98CFD6,#9AD0D7,#9BD1D7,#9DD1D8,#9ED2D8,#A0D3D9,#A1D3DA,#A3D4DA,#A4D5DB,#A6D5DB,#A7D6DC,#A9D7DD,#AAD7DD,#ACD8DE,#ADD9DE,#AFDADF,#B0DAE0,#B2DBE0,#B3DCE1,#B5DCE1,#B6DDE2,#B8DEE2,#B9DEE3,#BBDFE4,#BCE0E4,#BEE1E5,#BFE1E5,#C1E2E6,#C2E3E7,#C4E3E7,#C5E4E8,#C7E5E8,#C8E5E9,#CAE6EA,#CBE7EA,#CDE8EB,#CEE8EB,#D0E9EC,#D1EAED,#D3EAED,#D4EBEE,#D6ECEE,#D7ECEF,#D9EDF0,#DAEEF0,#DCEEF1,#DDEFF1,#DFF0F2,#E0F1F3,#E2F1F3,#E3F2F4,#E5F3F4,#E6F3F5,#E8F4F6,#E9F5F6,#EBF5F7,#ECF6F7,#EEF7F8,#EFF8F9,#F1F8F9,#F2F9FA,#F4FAFA,#F5FAFB,#F7FBFC,#F8FCFC,#FAFCFD,#FBFDFD,#FDFEFE,#FFFFFF"


 palettes = [
  {
    overall: "Greys",
    pallette1: p1,
    pallette2: "#FA8072",
    pallette3: "#FFE5B4",
    pallette4: "#c9c7b9",
    error_reason: {
      colors: ["#8DD3C7", "#FFFFB3", "#BEBADA", "#FFFFFF"],
      names: ["Memory limit exceeded", "Time limit exceeded", "Execution error", "No error"]
    }
  }
][0]  */

/* function transpose_list_of_objects(list) {
  return Object.fromEntries(Object.keys(list[0]).map(key => [key, list.map(d => d[key])]))
} */

/* funkyheatmap(
    transpose_list_of_objects(final_data),
    transpose_list_of_objects(column_info),
    [],
    transpose_list_of_objects(column_groups),
    [],
    palettes,
    {
        fontSize: 14,
        rowHeight: 26,
        rootStyle: 'max-width: none',
        colorByRank: color_by_rank,
        theme: {
            oddRowBackground: 'var(--bs-body-bg)',
            evenRowBackground: 'var(--bs-button-hover)',
            textColor: 'var(--bs-body-color)',
            strokeColor: 'var(--bs-body-color)',
            headerColor: 'var(--bs-body-color)',
            hoverColor: 'var(--bs-body-color)'
        }
    },
    scale_column
); */

``` -->

::: {.cell .panel-input .card .bg-light}
<details>

<summary>Display settings</summary>

```{ojs}
//| echo: false

viewof color_by_rank = Inputs.toggle({label: "Color by rank:", value: true})
viewof scale_column = Inputs.toggle({label: "Minmax column:", value: false})
viewof show_con = Inputs.toggle({label: "Show control methods:", value: true})
```

</details>

<details>

<summary>Filter methods</summary>

```{ojs}
//| echo: false

viewof method_ids = Inputs.checkbox(
  final_data.map(item => item.method),
  {
    label: "Methods:"
  } 
)

```  

</details>

<details>

<summary>Filter metrics</summary>

```{ojs}
//| echo: false

viewof metric_ids = Inputs.checkbox(
  Object.keys(final_data[0]),
  {
    label: "Metrics:"
  }
)
```

</details>
:::

```{ojs}
//| echo: false
//| warning: false


Inputs.table(final_data)
```


```{r}
#| echo: false
#| warning: false

library(tibble)
library(dplyr)

final_data_csv <- read_csv("./data/final_data.csv", show_col_types = FALSE)
# print("final_data_csv")
# print(final_data_csv)
final_data_csv$...1 <- NULL

datatable(
  final_data_csv,
  options = list(
    pageLength = 15,
    scrollX = TRUE,
    searching = TRUE,
    autoWidth = TRUE
    
  ),
  filter = "top",
  class = 'compact',
  style = 'bootstrap'
) %>%
  formatRound(columns = which(sapply(final_data_csv, is.numeric)), digits = 2)
```

